### ISSUE TITLE
onResponse doesn´t called after adding TikXmlConverterFactory.create

### ISSUE THREAD

**Issue by FabianTerhorst** [Tickaroo/tikxml#23] opened 2016-06-01 09:06 UTC
Im doing the following to create the TikXml object
```java
TikXml tikXml = new TikXml.Builder()
                .exceptionOnUnreadXml(false)
                .build();
```

adding the converter factory

```java
...
.addConverterFactory(TikXmlConverterFactory.create(tikXml));
...
```

My object
```java
@Xml(name = "myroottag", scanMode = ScanMode.ANNOTATIONS_ONLY)
public class ResultData {

    @com.tickaroo.tikxml.annotation.Path("profile")
    @com.tickaroo.tikxml.annotation.Element(name = "user")
    private User mUser;

}

@Xml(scanMode = ScanMode.ANNOTATIONS_ONLY)
public class User extends RealmObject implements IIdentifyable {

    @PrimaryKey
    @PropertyElement(name = "id")
    private int mIdentifier;
}
```

**Comment by FabianTerhorst** [comment] 2016-06-01 09:13
i have tried now to set @Xml(scanMode = ScanMode.ANNOTATIONS_ONLY, inheritance = false) for the use object, because of the realm object but still no result.

**Comment by FabianTerhorst** [comment] 2016-06-01 09:20
I got a exception now Unknown XmlToken: Peeked = 0

**Comment by FabianTerhorst** [comment] 2016-06-01 09:22
you want the xml output?

**Comment by sockeqwe** [comment] 2016-06-01 09:22
yes. please also attach a stacktrace.

**Comment by FabianTerhorst** [comment] 2016-06-01 09:25
```
 <?xml version="1.0" encoding="UTF-8" ?>
<myroottag><profile><user><id>1</id></user></profile></myroottag>
```

and the exception 

````
Caused by: java.lang.AssertionError: Unknown XmlToken: Peeked = 0
                                                                              at com.tickaroo.tikxml.XmlReader.peek(XmlReader.java:140)
                                                                              at com.tickaroo.tikxml.XmlReader.beginElement(XmlReader.java:330)
                                                                              at com.tickaroo.tikxml.TikXml.read(TikXml.java:100)
                                                                              at com.tickaroo.tikxml.retrofit.TikXmlResponseBodyConverter.convert(TikXmlResponseBodyConverter.java:44)
                                                                              at com.tickaroo.tikxml.retrofit.TikXmlResponseBodyConverter.convert(TikXmlResponseBodyConverter.java:32)
                                                                              at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:116)
                                                                              at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
                                                                              at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                              at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
                                                                              at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
                                                                              at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                              at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
                                                                              at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                              at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                              at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                              at rx.Observable.unsafeSubscribe(Observable.java:8460)
                                                                              at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                              at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
                                                                              at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
```

but the error isn´t comming again it was just a connection timeout that returned a empty xml. Still no response

**Comment by sockeqwe** [comment] 2016-06-01 09:33
`java.lang.AssertionError: Unknown XmlToken: Peeked = 0`  basically means that the input stream is empty I guess. What do you mean with 

> Still no response

No callback will be invoked? What CallApdatper do you use? `RxJava`? Which version of Retrofit do you use. Do you specify your own version of okhttp (which may include a newer version of okio)

**Comment by FabianTerhorst** [comment] 2016-06-01 09:34
even when im getting a xml onresponse doesn´t call. I have tried both Rxjava and Call enqueue. Im using version 2.0.2.

**Comment by sockeqwe** [comment] 2016-06-01 09:35
Does it work with `Retrofit 2.0.0`?

**Comment by FabianTerhorst** [comment] 2016-06-01 09:35
```java
getApi().getXmlCall().enqueue(new Callback<ResultData>() {
            @Override
            public void onResponse(Call<ResultData> call, retrofit2.Response<ResultData> response) {
                android.util.Log.d("response", response.body().toString());
            }

            @Override
            public void onFailure(Call<ResultData> call, Throwable t) {
                t.printStackTrace();
            }
        });
```

**Comment by FabianTerhorst** [comment] 2016-06-01 09:35
i will try

**Comment by FabianTerhorst** [comment] 2016-06-01 09:38
```compile 'com.squareup.retrofit2:retrofit:2.0.0' ``` doesn´t work.

**Comment by FabianTerhorst** [comment] 2016-06-01 09:39
is every exception printed?

**Comment by sockeqwe** [comment] 2016-06-01 09:44
yes, exceptions are not suppressed.

I'm sorry but I don't have time to debug that this week. Since it's annotation processing based, you can attach a debugger. Try to set a breakpoint in `com.tickaroo.tikxml.TikXml.read(TikXml.java:100)` and step through it as your xml data comes in. Maybe your backend is simply returning "nothing". In that case TikXml might return null.

**Comment by FabianTerhorst** [comment] 2016-06-01 10:11
with simplexml everythink is working, os it shouldn´t be null.

**Comment by FabianTerhorst** [comment] 2016-06-01 10:27
i don´t know if you have a limit for the xml size, but the current xml size is 41473-byte

**Comment by FabianTerhorst** [comment] 2016-06-01 10:31
But the annotation processor is working, he is throwing exceptions for thinks like setter for private fields or .exceptionOnUnreadXml(false)

**Comment by FabianTerhorst** [comment] 2016-06-01 10:45
I also using the logging interceptor to make sure the response is correct.

**Comment by sockeqwe** [comment] 2016-06-01 10:54
Not there is no limit regarding xml size. We are dealing with much bigger xmls successfully.
`exceptionOnUnreadXml(true)` only means that if there is a xml tag in your xml file then the parser will throw an exception if there is no mapping to a java class defined.

Setters and getters are automatically detected for private fields. Otherwise annotation processor will throw an exception (simply try it by you own: remove a setter method for a private field).

I still don't understand what you mean with: 

> Still no response

So you see that the http request is executed (http response and that you receive a response) by using logging interceptor, right? 
Is null returned from parser? will an exception be thrown? 

Have you tried to set a breakpoint at   `com.tickaroo.tikxml.TikXml.read(TikXml.java:100)` to see what the return value is and if the read() method has ever been executed?

**Comment by FabianTerhorst** [comment] 2016-06-01 11:40
the read method got executed, but the return is empty. The BufferedSource is a valid xml. I have tried to implement a own converter factory, but the result from tikXml.read is not null, because there is no crash when calling toString.

**Comment by FabianTerhorst** [comment] 2016-06-01 11:44
Any log after calling T data = tikXml.read(responseBody.source(), clazz); isn´t working anymore

**Comment by sockeqwe** [comment] 2016-06-01 11:49
What does `isn't working anymore` mean? Exception? null returned?

If you can give me a unit test reading your xml (simply create a String containing your xml and create a BufferedSource out of it) then I will debug an fix it for you.

**Comment by FabianTerhorst** [comment] 2016-06-01 11:53
i will create a unit test for you

**Comment by FabianTerhorst** [comment] 2016-06-01 12:03
GC_FOR_ALLOC freed 218K, 4% free 9303K/9640K, paused 14ms, total 14ms its freezes the app forever in ui thread.

**Comment by FabianTerhorst** [comment] 2016-06-01 12:06
This is the same behavior that gson has when convert json to a realm object

**Comment by FabianTerhorst** [comment] 2016-06-01 12:08
when im removing extends RealmObject its working

**Comment by FabianTerhorst** [comment] 2016-06-01 12:09
gson has a exclude strategy for that 
````
.setExclusionStrategies(new ExclusionStrategy() {
            @Override
            public boolean shouldSkipField(FieldAttributes f) {
                return f.getDeclaringClass().equals(RealmObject.class);
            }

            @Override
            public boolean shouldSkipClass(Class<?> clazz) {
                return false;
            }
        })
```

**Comment by FabianTerhorst** [comment] 2016-06-01 12:18
But when im loading the real xml(bigger) from retrofit its start freezing again.

**Comment by sockeqwe** [comment] 2016-06-01 12:21
I see. Realm is doing some byte code manipulation that might causes this issue. 

I have to figure out why you have to exclude `RealmObject` by using `.setExclusionStrategies()`, but since annotation processing runs before Realm is adding a field RealmObject  (byte manipulation)  this is not easy.

I also think that Realm is adding byte code for getters and setters which might cause problems since TikXml uses those as well if you have annotated private fields with TikXml annotations. You could try to change visibility of your annotated fields to package (default visibility).

Otherwise, create a class just for parsing xml and then copy it into a RealmClass ...

**Comment by FabianTerhorst** [comment] 2016-06-01 12:23
its also possible to use the RealmModel interface, with this the data also loads.

**Comment by FabianTerhorst** [comment] 2016-06-01 12:25
```
@RealmClass
public class User implements RealmModel, IIdentifyable
```
 looks like the cleanest implementation

**Comment by FabianTerhorst** [comment] 2016-06-01 12:37
i know why the big xml is not loading. There is a json value inside a tag. Looks like that this string is to big for the buffer.

**Comment by FabianTerhorst** [comment] 2016-06-01 12:54
you want to see the json?

**Comment by sockeqwe** [comment] 2016-06-01 12:57
yes and also the exception stacktrace please ...

Fabian Terhorst <notifications@github.com> schrieb am Mi., 1. Juni 2016,
14:54:

**Comment by FabianTerhorst** [comment] 2016-06-01 13:00
there is no stacktrace only a freeze. <![CDATA[[{"type":"control","x":352,"y":100,"deviceid":7},{"x0":255,"y0":90,"x1":422.19,"y1":62.14,"type":"wall"},{"x0":525,"y0":45,"x1":499.68,"y1":101.97,"type":"wall"},{"x0":465,"y0":180,"x1":330,"y1":180,"type":"wall"},{"x0":330,"y0":180,"x1":255,"y1":90,"type":"wall"},{"x0":422.19,"y0":62.14,"x1":487.38,"y1":51.27,"type":"window"},{"x0":487.38,"y0":51.27,"x1":525,"y1":45,"type":"wall"},{"x0":499.68,"y0":101.97,"x1":487.23,"y1":129.99,"type":"window"},{"x0":487.23,"y0":129.99,"x1":465,"y1":180,"type":"wall"},{"type":"control","x":623,"y":211,"deviceid":1}]]] this json is working there is another thats the 50x.

**Comment by sockeqwe** [comment] 2016-06-01 13:08
The only thing that drives me nuts is that it freezes ... that definitely
should not happen. I can't really say what the problem is without a
stacktrace. Maybe there is a problem with CDATA in general and the
exception was caught somewhere.

Fabian Terhorst <notifications@github.com> schrieb am Mi., 1. Juni 2016,
15:00:

**Comment by FabianTerhorst** [comment] 2016-06-01 13:09
im using CDATA on another places too. But there are working.

**Comment by FabianTerhorst** [comment] 2016-06-01 13:10
And the smaller json doesn´t trigger the error.

**Comment by FabianTerhorst** [comment] 2016-06-01 13:33
add <json><![CDATA[[{"x0":45,"y0":390,"x1":45,"y1":45,"type":"wall"},{"x0":240.25,"y0":45,"x1":240,"y1":45,"type":"window"},{"x0":45,"y0":45,"x1":600,"y1":45,"type":"wall"},{"x0":600,"y0":390,"x1":45,"y1":390,"type":"wall"},{"x0":105,"y0":390,"x1":105,"y1":300,"type":"wall"},{"x0":105,"y0":300,"x1":165,"y1":300,"type":"wall"},{"x0":165,"y0":300,"x1":165,"y1":390,"type":"wall"},{"x0":240,"y0":390,"x1":240,"y1":300,"type":"wall"},{"x0":240,"y0":300,"x1":300,"y1":300,"type":"wall"},{"x0":300,"y0":300,"x1":300,"y1":390,"type":"wall"},{"x0":300,"y0":300,"x1":360,"y1":300,"type":"wall"},{"x0":360,"y0":300,"x1":360,"y1":390,"type":"wall"},{"x0":360,"y0":300,"x1":420,"y1":300,"type":"wall"},{"x0":420,"y0":300,"x1":420,"y1":390,"type":"wall"},{"x0":105,"y0":270,"x1":105,"y1":180,"type":"wall"},{"x0":105,"y0":180,"x1":165,"y1":180,"type":"wall"},{"x0":165,"y0":180,"x1":225,"y1":180,"type":"wall"},{"x0":225,"y0":180,"x1":225,"y1":270,"type":"wall"},{"x0":225,"y0":270,"x1":105,"y1":270,"type":"wall"},{"x0":510,"y0":300,"x1":510,"y1":390,"type":"wall"},{"x0":510,"y0":390,"x1":570,"y1":390,"type":"wall"},{"x0":570,"y0":390,"x1":570,"y1":300,"type":"wall"},{"x0":570,"y0":300,"x1":510,"y1":300,"type":"wall"},{"x0":600,"y0":390,"x1":630,"y1":390,"type":"wall"},{"x0":630,"y0":390,"x1":630,"y1":45,"type":"wall"},{"x0":630,"y0":45,"x1":600,"y1":45,"type":"wall"},{"x0":570,"y0":270,"x1":570,"y1":180,"type":"wall"},{"x0":570,"y0":180,"x1":510,"y1":180,"type":"wall"},{"x0":510,"y0":180,"x1":510,"y1":270,"type":"wall"},{"x0":510,"y0":270,"x1":450,"y1":270,"type":"wall"},{"x0":450,"y0":270,"x1":450,"y1":180,"type":"wall"},{"x0":450,"y0":180,"x1":510,"y1":180,"type":"wall"},{"x0":510,"y0":270,"x1":570,"y1":270,"type":"wall"},{"x0":105,"y0":60,"x1":105,"y1":90,"type":"wall"},{"x0":105,"y0":90,"x1":165,"y1":90,"type":"wall"},{"x0":225,"y0":60,"x1":225,"y1":90,"type":"wall"},{"x0":225,"y0":90,"x1":165,"y1":90,"type":"wall"},{"x0":570,"y0":60,"x1":510,"y1":60,"type":"wall"},{"x0":510,"y0":60,"x1":510,"y1":90,"type":"wall"},{"x0":510,"y0":90,"x1":450,"y1":90,"type":"wall"},{"x0":450,"y0":90,"x1":450,"y1":60,"type":"wall"},{"x0":450,"y0":60,"x1":510,"y1":60,"type":"wall"},{"x0":510,"y0":90,"x1":570,"y1":90,"type":"wall"},{"x0":570,"y0":90,"x1":570,"y1":60,"type":"wall"},{"x0":270,"y0":60,"x1":270,"y1":90,"type":"wall"},{"x0":270,"y0":90,"x1":330,"y1":90,"type":"wall"},{"x0":330,"y0":90,"x1":330,"y1":60,"type":"wall"},{"x0":330,"y0":60,"x1":390,"y1":60,"type":"wall"},{"x0":390,"y0":60,"x1":390,"y1":90,"type":"wall"},{"x0":390,"y0":90,"x1":330,"y1":90,"type":"wall"},{"x0":270,"y0":60,"x1":330,"y1":60,"type":"wall"},{"x0":45,"y0":105,"x1":630,"y1":105,"type":"wall"},{"x0":630,"y0":105,"x1":630,"y1":165,"type":"wall"},{"x0":630,"y0":165,"x1":45,"y1":165,"type":"wall"},{"x0":60,"y0":105,"x1":60,"y1":165,"type":"wall"},{"x0":60,"y0":165,"x1":75,"y1":165,"type":"wall"},{"x0":75,"y0":165,"x1":75,"y1":105,"type":"wall"},{"x0":75,"y0":105,"x1":90,"y1":105,"type":"wall"},{"x0":90,"y0":105,"x1":90,"y1":165,"type":"wall"},{"x0":90,"y0":165,"x1":105,"y1":165,"type":"wall"},{"x0":105,"y0":165,"x1":105,"y1":105,"type":"wall"},{"x0":105,"y0":105,"x1":120,"y1":105,"type":"wall"},{"x0":120,"y0":105,"x1":120,"y1":165,"type":"wall"},{"x0":120,"y0":165,"x1":135,"y1":165,"type":"wall"},{"x0":135,"y0":165,"x1":135,"y1":105,"type":"wall"},{"x0":135,"y0":105,"x1":150,"y1":105,"type":"wall"},{"x0":150,"y0":105,"x1":150,"y1":165,"type":"wall"},{"x0":150,"y0":165,"x1":165,"y1":165,"type":"wall"},{"x0":165,"y0":165,"x1":165,"y1":105,"type":"wall"},{"x0":165,"y0":105,"x1":180,"y1":105,"type":"wall"},{"x0":180,"y0":105,"x1":180,"y1":165,"type":"wall"},{"x0":180,"y0":165,"x1":195,"y1":165,"type":"wall"},{"x0":195,"y0":165,"x1":195,"y1":105,"type":"wall"},{"x0":195,"y0":105,"x1":210,"y1":105,"type":"wall"},{"x0":210,"y0":105,"x1":210,"y1":165,"type":"wall"},{"x0":210,"y0":165,"x1":225,"y1":165,"type":"wall"},{"x0":225,"y0":165,"x1":225,"y1":105,"type":"wall"},{"x0":225,"y0":105,"x1":240,"y1":105,"type":"wall"},{"x0":240,"y0":105,"x1":240,"y1":165,"type":"wall"},{"x0":240,"y0":165,"x1":255,"y1":165,"type":"wall"},{"x0":255,"y0":165,"x1":255,"y1":105,"type":"wall"},{"x0":255,"y0":105,"x1":270,"y1":105,"type":"wall"},{"x0":270,"y0":105,"x1":270,"y1":165,"type":"wall"},{"x0":270,"y0":165,"x1":285,"y1":165,"type":"wall"},{"x0":285,"y0":165,"x1":285,"y1":105,"type":"wall"},{"x0":285,"y0":105,"x1":300,"y1":105,"type":"wall"},{"x0":300,"y0":105,"x1":300,"y1":165,"type":"wall"},{"x0":300,"y0":165,"x1":315,"y1":165,"type":"wall"},{"x0":315,"y0":165,"x1":315,"y1":105,"type":"wall"},{"x0":315,"y0":105,"x1":330,"y1":105,"type":"wall"},{"x0":330,"y0":105,"x1":330,"y1":165,"type":"wall"},{"x0":330,"y0":165,"x1":345,"y1":165,"type":"wall"},{"x0":345,"y0":165,"x1":345,"y1":105,"type":"wall"},{"x0":345,"y0":105,"x1":360,"y1":105,"type":"wall"},{"x0":360,"y0":105,"x1":360,"y1":165,"type":"wall"},{"x0":360,"y0":165,"x1":375,"y1":165,"type":"wall"},{"x0":375,"y0":165,"x1":375,"y1":105,"type":"wall"},{"x0":375,"y0":105,"x1":390,"y1":105,"type":"wall"},{"x0":390,"y0":105,"x1":390,"y1":165,"type":"wall"},{"x0":390,"y0":165,"x1":405,"y1":165,"type":"wall"},{"x0":405,"y0":165,"x1":405,"y1":105,"type":"wall"},{"x0":405,"y0":105,"x1":420,"y1":105,"type":"wall"},{"x0":420,"y0":105,"x1":420,"y1":165,"type":"wall"},{"x0":420,"y0":165,"x1":435,"y1":165,"type":"wall"},{"x0":435,"y0":165,"x1":435,"y1":105,"type":"wall"},{"x0":435,"y0":105,"x1":450,"y1":105,"type":"wall"},{"x0":450,"y0":105,"x1":450,"y1":165,"type":"wall"},{"x0":450,"y0":165,"x1":465,"y1":165,"type":"wall"},{"x0":465,"y0":165,"x1":465,"y1":105,"type":"wall"},{"x0":465,"y0":105,"x1":480,"y1":105,"type":"wall"},{"x0":480,"y0":105,"x1":480,"y1":165,"type":"wall"},{"x0":480,"y0":165,"x1":495,"y1":165,"type":"wall"},{"x0":495,"y0":165,"x1":495,"y1":105,"type":"wall"},{"x0":495,"y0":105,"x1":510,"y1":105,"type":"wall"},{"x0":510,"y0":105,"x1":510,"y1":165,"type":"wall"},{"x0":510,"y0":165,"x1":525,"y1":165,"type":"wall"},{"x0":525,"y0":165,"x1":525,"y1":105,"type":"wall"},{"x0":525,"y0":105,"x1":540,"y1":105,"type":"wall"},{"x0":540,"y0":105,"x1":540,"y1":165,"type":"wall"},{"x0":540,"y0":165,"x1":555,"y1":165,"type":"wall"},{"x0":555,"y0":165,"x1":555,"y1":105,"type":"wall"},{"x0":555,"y0":105,"x1":570,"y1":105,"type":"wall"},{"x0":570,"y0":105,"x1":570,"y1":165,"type":"wall"},{"x0":570,"y0":165,"x1":585,"y1":165,"type":"wall"},{"x0":585,"y0":165,"x1":585,"y1":105,"type":"wall"},{"x0":585,"y0":105,"x1":600,"y1":105,"type":"wall"},{"x0":600,"y0":105,"x1":600,"y1":165,"type":"wall"},{"x0":600,"y0":165,"x1":615,"y1":165,"type":"wall"},{"x0":615,"y0":165,"x1":615,"y1":105,"type":"wall"},{"x0":105,"y0":60,"x1":225,"y1":60,"type":"wall"},{"x0":165,"y0":60,"x1":165,"y1":90,"type":"wall"},{"x0":165,"y0":180,"x1":165,"y1":270,"type":"wall"},{"x0":720,"y0":390,"x1":1020,"y1":390,"type":"wall"},{"x0":1020,"y0":390,"x1":1020,"y1":165,"type":"wall"},{"x0":1020,"y0":165,"x1":720,"y1":165,"type":"wall"},{"x0":720,"y0":165,"x1":720,"y1":390,"type":"wall"},{"x0":720,"y0":300,"x1":735,"y1":300,"type":"wall"},{"x0":735,"y0":300,"x1":735,"y1":165,"type":"wall"},{"x0":735,"y0":165,"x1":750,"y1":165,"type":"wall"},{"x0":750,"y0":165,"x1":750,"y1":300,"type":"wall"},{"x0":750,"y0":300,"x1":765,"y1":300,"type":"wall"},{"x0":765,"y0":300,"x1":765,"y1":165,"type":"wall"},{"x0":765,"y0":165,"x1":780,"y1":165,"type":"wall"},{"x0":780,"y0":165,"x1":780,"y1":300,"type":"wall"},{"x0":780,"y0":300,"x1":795,"y1":300,"type":"wall"},{"x0":795,"y0":300,"x1":795,"y1":165,"type":"wall"},{"x0":795,"y0":165,"x1":810,"y1":165,"type":"wall"},{"x0":810,"y0":165,"x1":810,"y1":300,"type":"wall"},{"x0":810,"y0":300,"x1":825,"y1":300,"type":"wall"},{"x0":825,"y0":300,"x1":825,"y1":165,"type":"wall"},{"x0":825,"y0":165,"x1":840,"y1":165,"type":"wall"},{"x0":840,"y0":165,"x1":840,"y1":300,"type":"wall"},{"x0":840,"y0":300,"x1":855,"y1":300,"type":"wall"},{"x0":855,"y0":300,"x1":855,"y1":165,"type":"wall"},{"x0":855,"y0":165,"x1":870,"y1":165,"type":"wall"},{"x0":870,"y0":165,"x1":870,"y1":300,"type":"wall"},{"x0":870,"y0":300,"x1":885,"y1":300,"type":"wall"},{"x0":885,"y0":300,"x1":885,"y1":165,"type":"wall"},{"x0":885,"y0":165,"x1":900,"y1":165,"type":"wall"},{"x0":900,"y0":165,"x1":900,"y1":300,"type":"wall"},{"x0":900,"y0":300,"x1":915,"y1":300,"type":"wall"},{"x0":915,"y0":300,"x1":915,"y1":165,"type":"wall"},{"x0":915,"y0":165,"x1":930,"y1":165,"type":"wall"},{"x0":930,"y0":165,"x1":930,"y1":300,"type":"wall"},{"x0":930,"y0":300,"x1":945,"y1":300,"type":"wall"},{"x0":945,"y0":300,"x1":945,"y1":165,"type":"wall"},{"x0":945,"y0":165,"x1":960,"y1":165,"type":"wall"},{"x0":960,"y0":165,"x1":960,"y1":300,"type":"wall"},{"x0":960,"y0":300,"x1":975,"y1":300,"type":"wall"},{"x0":975,"y0":300,"x1":975,"y1":165,"type":"wall"},{"x0":975,"y0":165,"x1":990,"y1":165,"type":"wall"},{"x0":990,"y0":165,"x1":990,"y1":300,"type":"wall"},{"x0":990,"y0":300,"x1":1005,"y1":300,"type":"wall"},{"x0":1005,"y0":300,"x1":1005,"y1":165,"type":"wall"},{"x0":720,"y0":300,"x1":1020,"y1":300,"type":"wall"},{"x0":735,"y0":390,"x1":735,"y1":300,"type":"wall"},{"x0":735,"y0":300,"x1":870,"y1":300,"type":"wall"},{"x0":900,"y0":390,"x1":1005,"y1":390,"type":"wall"},{"x0":1005,"y0":390,"x1":1005,"y1":300,"type":"wall"},{"x0":840,"y0":390,"x1":885,"y1":390,"type":"wall"},{"x0":885,"y0":390,"x1":885,"y1":300,"type":"wall"},{"x0":855,"y0":390,"x1":855,"y1":300,"type":"wall"},{"x0":150,"y0":240,"x1":165,"y1":210,"type":"wall"},{"x0":165,"y0":210,"x1":180,"y1":240,"type":"wall"},{"x0":180,"y0":225,"x1":150,"y1":225,"type":"wall"},{"x0":150,"y0":75,"x1":150,"y1":90,"type":"wall"},{"x0":135,"y0":75,"x1":165,"y1":75,"type":"wall"},{"x0":750,"y0":330,"x1":750,"y1":360,"type":"wall"},{"x0":735,"y0":330,"x1":765,"y1":330,"type":"wall"},{"x0":780,"y0":330,"x1":780,"y1":360,"type":"wall"},{"x0":825,"y0":330,"x1":795,"y1":330,"type":"wall"},{"x0":795,"y0":330,"x1":795,"y1":360,"type":"wall"},{"x0":795,"y0":360,"x1":825,"y1":360,"type":"wall"},{"x0":825,"y0":360,"x1":825,"y1":345,"type":"wall"},{"x0":825,"y0":345,"x1":810,"y1":345,"type":"wall"},{"x0":915,"y0":330,"x1":915,"y1":360,"type":"wall"},{"x0":915,"y0":360,"x1":915,"y1":330,"type":"wall"},{"x0":915,"y0":330,"x1":945,"y1":330,"type":"wall"},{"x0":945,"y0":330,"x1":945,"y1":345,"type":"wall"},{"x0":945,"y0":345,"x1":915,"y1":345,"type":"wall"}]]]></json> to your xml the read won´t work anymore. This is the medium size.

**Comment by FabianTerhorst** [comment] 2016-06-01 13:54
https://github.com/Tickaroo/tikxml/blob/master/core/src/main/java/com/tickaroo/tikxml/XmlReader.java#L645 this could be the problem?

**Comment by FabianTerhorst** [comment] 2016-06-01 14:19
json arrayis also using ]

**Comment by sockeqwe** [comment] 2016-06-01 14:30
Maybe that is the issue, as already said, i don't have time to work on that
this week. If you have a look at the unit tests in this github repo you
will see some simple tests reading xml from string. If you can provide me a
failing unit test containig cdata + json array i am able to fix it within a
few hours. Otherwise, you have to wait until next week ...

Fabian Terhorst <notifications@github.com> schrieb am Mi., 1. Juni 2016,
16:19:

**Comment by FabianTerhorst** [comment] 2016-06-01 15:20
```java
public void jsonArray() throws IOException {
        android.util.Log.d("start","parsing");
        String xml = "<element><json><![CDATA[[{a:'b'}, {b:'c'}]]]></json></element>";
        JsonObject jsonObject = readerFrom(xml);
        android.util.Log.d("json", jsonObject.json);
    }

    public static JsonObject readerFrom(String xml) throws IOException {
        TikXml tikXml = new TikXml.Builder().build();
        Buffer buffer = new Buffer();
        buffer.writeUtf8(xml);
        return tikXml.read(buffer, JsonObject.class);
    }
```

```java
public @Xml(name = "element")
class JsonObject {
    @PropertyElement(name = "json")
    String json;
}
```

is freezing the thread 10/10.

**Closed** 2016-06-01 22:17 UTC
