### ISSUE TITLE
exception while reading rss feed

### ISSUE THREAD

**Issue by namdroid** [Tickaroo/tikxml#144] opened 2020-04-04 20:10 UTC
I get this exception with custom converter in retrofit:

 java.lang.AssertionError: Unknown XmlToken: Peeked = 0
        at com.tickaroo.tikxml.XmlReader.peek(XmlReader.java:149)
        at com.tickaroo.tikxml.XmlReader.beginElement(XmlReader.java:341)
        at com.tickaroo.tikxml.TikXml.read(TikXml.java:110)

**Comment by sockeqwe** [comment] 2020-04-05 07:54
which Version of tikxml do you use?
also, is the RSS feed empty?

**Comment by namdroid** [comment] 2020-04-09 16:43
It works with other XmlConverterFactory but i get the error with TikXmlConverterFactory. It may not work with CoroutineCallAdapterFactory ?

I use 
         .addCallAdapterFactory(CoroutineCallAdapterFactory())
            .addConverterFactory(
                TikXmlConverterFactory.create(
                    TikXml.Builder().exceptionOnUnreadXml(false).build()
                )
            )

and 

    @GET
    fun getRssRemote(@Url url: String): Deferred<Response<RssRemote>>


E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    java.lang.AssertionError: Unknown XmlToken: Peeked = 0
        at com.tickaroo.tikxml.XmlReader.peek(XmlReader.java:149)
        at com.tickaroo.tikxml.XmlReader.beginElement(XmlReader.java:341)
        at com.tickaroo.tikxml.TikXml.read(TikXml.java:110)
        at com.tickaroo.tikxml.retrofit.TikXmlResponseBodyConverter.convert(TikXmlResponseBodyConverter.java:44)
        at com.tickaroo.tikxml.retrofit.TikXmlResponseBodyConverter.convert(TikXmlResponseBodyConverter.java:32)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by ismaeldivita** [comment] 2020-04-10 09:58
Got the same error parsing RSS.
Fixed by bumping to the 0.9.0_8-SNAPSHOT

But now I'm facing others erros on specific feeds, but I need to double check if it's not something on my side.

**Comment by sockeqwe** [comment] 2020-04-10 11:26
@ismaeldivita  can you also provide the annotated classes so that we can run test / debug it

**Comment by ismaeldivita** [comment] 2020-04-10 11:36
Sure.

This is the package containing the classes. https://github.com/ismaeldivita/audiow/tree/master/podcast/podcast_service/src/main/java/audiow/podcast/service/itunes/parser/xml/model

The rss above works with `0.9.0_8-SNAPSHOT` but not with `0.8.15`
```Unknown XmlToken: Peeked = 0```

But now I'm facing other issues with `0.9.0_8-SNAPSHOT`.

Like for this one https://radiofobia.com.br/podcast/category/podcast/classics/feed/
```java.io.IOException: Unterminated comment at path /rss/channel/item/category/text() - {}```

I'm still trying to figure out if it's something on my side

**Comment by sockeqwe** [comment] 2020-04-11 11:12
@ismaeldivita  I cannot reproduce your issue. Take a look here (I have created a branch called `114_unterminated_comment` for your request):
https://github.com/Tickaroo/tikxml/blob/114_unterminated_comment/annotationprocessortesting-kt/src/test/java/com/tickaroo/tikxml/regressiontests/unterminatedcomment/UnterminateCommentTest.kt


Can you provide me a failing test?

Also possible that this was actually a misformed RSS feed that the author fixed over night?

**Closed by sockeqwe** 2020-04-11 11:12 UTC

**Comment by sockeqwe** [comment] 2020-04-12 19:11
@ismaeldivita actually there was a bug with CDATA.
This PR solves it: https://github.com/Tickaroo/tikxml/pull/146
