### ISSUE TITLE
Specify order of elements/attributes

### ISSUE THREAD

**Issue by red-coracle** [Tickaroo/tikxml#90] opened 2018-08-14 01:51 UTC
I sometimes need to be able to set a specific order of elements when serializing XML. Unless I've missed a method to achieve that right now, it would be helpful to introduce an annotation similar to the Simple framework's [@Order](http://simple.sourceforge.net/download/stream/doc/javadoc/org/simpleframework/xml/Order.html) annotation.

**Comment by sockeqwe** [comment] 2018-08-14 15:43
The order is specified in the order you define your fields / getters in
your source code. Isn't it enough?

red-coracle <notifications@github.com> schrieb am Di., 14. Aug. 2018, 03:51:

**Comment by red-coracle** [comment] 2018-08-14 23:59
I'm not very familiar with Java so I could be doing it wrong, but in this example the `<authentication>`  block always comes second for me.

```
@Xml
public class Operation {
    @Element
    public Authentication authentication;

    @Element
    public Content content;

    public Operation() {
        this.authentication = new Authentication();
        this.content = new Content();
    }
}
```

**Comment by sockeqwe** [comment] 2018-08-16 08:58
Yeah that ordering should be enough. I haven't tested it yet but I think we should fix this in the annotation processor instead of adding a `@Order` annotation unless there is really a strong need for overriding the "default ordering" as defined in the `.java` file (which I don't think there is a strong use case for it).

**Comment by a-severin** [comment] 2018-09-07 21:00
I have the same issue to use tikxml on android. soap services require xml elements order.

**Comment by WeaponMan** [comment] 2018-09-07 21:39
@sockeqwe It easy fix if you don't count fixing order in tests. Just replace `HashMap` with `LinkedHashMap` in places like this one:
```java
override val attributes = HashMap<String, AttributeField>()
override val childElements = HashMap<String, XmlChildElement>()
```

**Comment by sockeqwe** [comment] 2018-10-05 14:33
#103 is merged latest SNAPSHOT contains this. I'm preparing a release beginning of next week.

**Closed** 2018-10-24 14:32 UTC

**Comment by vikky9393** [comment] 2018-10-30 21:18
When will the next snapshot be available? This is still an outstanding issue in the current SNAPSHOT.

**Comment by sockeqwe** [comment] 2018-10-30 23:08
Whenever something is pushed to master our CI system creeates a ne2
snapshot. If that is not the case, something in our CI pipeline is broken.
I will check that tomorrow.

Vikram Velma <notifications@github.com> schrieb am Di., 30. Okt. 2018,
22:19:

**Comment by StPatrck** [comment] 2018-11-05 17:06
Just wanted to note that this fix is still not available. The latest available snapshot is still 8.14.

**Comment by sockeqwe** [comment] 2018-11-06 08:07
Right, we are migrating from maven to gradle right now. In the meantime you
can use jitpack.io and link to the lateet commit. Sorry for the
inconveniences, gradle migration should be completed soon (integration
tests for generated code / annotation processor are not working yet with
gradle, thats the only thing that is missing to complete migration)

Patrick Honkonen <notifications@github.com> schrieb am Mo., 5. Nov. 2018,
18:06:

**Comment by maxlord** [comment] 2018-12-20 23:13
@sockeqwe please publish annotation artifact with version 0.8.15.

**Comment by msecilmis** [comment] 2019-02-28 07:42
Is there a progress on this? Latest version doesn't have the correct ordering.

**Comment by sockeqwe** [comment] 2019-02-28 12:14
I'm looking into this tonight

**Comment by sockeqwe** [comment] 2019-03-03 11:37
Could you please give `0.8.16-SNAPSHOT` a try. I just updated the latest SNAPSHOT. Should work with that version.

**Comment by msecilmis** [comment] 2019-03-07 11:07
Now i'm getting the No TypeAdapter for class *** found. Expected name of the type adapter is ***$$TypeAdapter . 

And i checked, i found the type adapter in generated folder.

**Comment by sockeqwe** [comment] 2019-03-11 15:48
Oh no, it looks there is an issue somewhere else in our code.

msecilmis <notifications@github.com> schrieb am Do., 7. März 2019 um
12:07 Uhr:

**Comment by bansal70** [comment] 2019-03-25 13:00
Is the issue resolved in "0.8.16-SNAPSHOT" version? As I'm still getting the same exception, "No TypeAdapter for class *** found. Expected name of the type adapter is ***$$TypeAdapter ."

**Comment by msecilmis** [comment] 2019-03-28 14:04
@sockeqwe should we reopen this issue? Someone might want to take it?

**Comment by sockeqwe** [comment] 2019-03-28 14:06
The issue is a different one. There seems to be a bug in 0.8.15 and 0.8.16 that doesn't generate the TypeAdapters properly. This is not related to the order of elements.
